### ISSUE TITLE
citation

### ISSUE THREAD

**Issue by vwoloszyn** [UKPLab/emnlp2017-claim-identification#1]
Hi, Is there any paper describing your - interesting - implementation that I could cite? 
Best,
Vinicius

**Comment by SteffenEger** [comment]
Indeed, Vinicius, you can cite this:
@InProceedings{Daxenberger.et.al.2017.EMNLP,
  title     = {What is the Essence of a Claim? Cross-Domain Claim Identification},
  author    = {Daxenberger, Johannes and Eger, Steffen and Habernal, Ivan and
               Stab, Christian and Gurevych, Iryna},
  booktitle = {Proceedings of the 2017 Conference on Empirical Methods
               in Natural Language Processing (EMNLP)},
  pages     = {to appear},
  month     = sep,
  year      = {2017},
  address   = {Copenhagen, Denmark},
  publisher = {Association for Computational Linguistics},
  url       = {https://arxiv.org/abs/1704.07203}
}

Best :)
